# Generated by Django 4.1 on 2022-09-14 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Family1',
            new_name='Family3',
        ),
    ]
